### PR TITLE
Feature/ransac

### PR DESCRIPTION
**Pull request by peacekurella**
Added RANSAC filtering in Utils.kt

### CODE REVIEW

**Review by mandakinee — APPROVED** [review]
Looks ok to me..

**Review by mandakinee — APPROVED** [review]
Looks ok to me..

**Comment by yashsriram** [comment]
Seems like a good start.
A few things,
1. I have added 'x' and 'c' keys to toggle drawing lasers and walls in master. You can turn off drawing lasers and walls to check your method thoroughly by moving here and there in the scene.
2. I think the FPS drop to ~49. This is fine for now. But can the code be optimized? We need to do more computation later so it might be useful to do simple optimizations rn. The simplest and most effective one would be to minimize new heap allocations.
3. I think least squares line fitting and landmark detection are left. So let's merge this into master after that maybe.

**Comment by peacekurella** [comment]
> Seems like a good start.
> A few things,
> 
> 1. I have added 'x' and 'c' keys to toggle drawing lasers and walls in master. You can turn off drawing lasers and walls to check your method thoroughly by moving here and there in the scene.
> 2. I think the FPS drop to ~49. This is fine for now. But can the code be optimized? We need to do more computation later so it might be useful to do simple optimizations rn. The simplest and most effective one would be to minimize new heap allocations.
> 3. I think least squares line fitting and landmark detection are left. So let's merge this into master after that maybe.

2. RANSAC would need at least 1000 iterations to be useful, so I do not see any way around that. Maybe try rendering with the GPU (Although I am not sure how useful that would be as I suspect we are bottlenecked by the CPU ? ) 

3. RANSAC is enough to extract lines from the points, I do not see the need for additional line fitting steps

**Review by mandakinee — APPROVED** [review]

**Pull request merged**
